const products = [
  {
    id: 1,
    name: "Ashwagandha",
    especie: "Withania somnifera",
    Precio: 4700,
    Cantidad: "50g",
    img: "/imgProducts/Ashwagandha.jpeg",
  },
  {
    id: 2,
    name: "Cordyceps",
    especie: "Cordyceps sinensis",
    Precio: 4300,
    Cantidad: "50g",
    img: "/imgProducts/cordyceps.jpeg",
  },
  {
    id: 3,
    name: "Eleutero",
    especie: "Eleutherococcus senticosus",
    Precio: 3500,
    Cantidad: "50g",
    img: "/imgProducts/Eleutero.jpeg",
  },
  {
    id: 4,
    name: "Ginseng",
    especie: "Panax ginseng, Panax quinquefolius",
    Precio: 2500,
    Cantidad: "50g",
    img: "/imgProducts/PanaxGinseng.jpeg",
  },
  {
    id: 5,
    name: "Albahaca Sagrada",
    especie: "Ocimum tenuiflorum, Ocimum sanctum",
    Precio: 2500,
    Cantidad: "50g",
    img: "/imgProducts/AlbahacaSagrada.jpeg",
  },
  {
    id: 6,
    name: "Regaliz",
    especie: "Glycyrrhiza glabra",
    Precio: 3000,
    Cantidad: "50g",
    img: "/imgProducts/Regaliz.jpeg",
  },
  {
    id: 7,
    name: "Rhodiola",
    especie: "Rhodiola Rosea",
    Precio: 2800,
    Cantidad: "50g",
    img: "/imgProducts/Rhodiola.jpeg",
  },
  {
    id: 8,
    name: "Schisandra",
    especie: "Schisandra chinensis",
    Precio: 3400,
    Cantidad: "50g",
    img: "/imgProducts/Schisandra.jpeg",
  },
  {
    id: 9,
    name: "Shilajit",
    especie: "Betún de Asfalto",
    Precio: 3200,
    Cantidad: "50g",
    img: "/imgProducts/Shilajit.jpeg",
  },
];

export { products }